/* compile.vala
 *
 * SPEC section 10, checklist items 10-15. The golden-file comparison is the
 * decisive one: if the generator reproduces docs/demo.docker-compose.yml from
 * the demo topology, the compiler is correct.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

using NetworkingLab.Core;

private string golden (string name) {
    var dir = Environment.get_variable ("NETLAB_TEST_DATA");
    if (dir == null) {
        error ("NETLAB_TEST_DATA is not set — the golden fixture cannot be found");
    }

    string contents;
    try {
        FileUtils.get_contents (Path.build_filename (dir, name), out contents);
    } catch (Error e) {
        error ("could not read fixture %s: %s", name, e.message);
    }
    return contents;
}

private int count (string haystack, string needle) {
    var seen = 0;
    var index = 0;
    while (true) {
        var found = haystack.index_of (needle, index);
        if (found < 0) {
            break;
        }
        seen++;
        index = found + needle.length;
    }
    return seen;
}

private bool has_line (string yaml, string line) {
    return ("\n" + yaml).contains ("\n" + line + "\n");
}

void test_demo_matches_the_golden_file () {
    var result = compile (demo_state ());

    /* The demo has to generate cleanly — it is the reference topology. */
    assert (result.warnings.length == 0);

    var expected = golden ("demo.docker-compose.yml");
    if (result.yaml == expected) {
        return;
    }

    /* Report the first differing line rather than dumping both files. Marking
       the test failed and returning keeps the message: asserting here would
       abort before TAP writes it out. */
    var actual_lines = result.yaml.split ("\n");
    var expected_lines = expected.split ("\n");
    for (var i = 0; i < int.max (actual_lines.length, expected_lines.length); i++) {
        var a = i < actual_lines.length ? actual_lines[i] : "<end of file>";
        var b = i < expected_lines.length ? expected_lines[i] : "<end of file>";
        if (a != b) {
            Test.fail_printf ("line %d differs:\n  expected: %s\n    actual: %s", i + 1, b, a);
            return;
        }
    }
    Test.fail_printf ("output differs from the golden file only in length");
}

/* A second fixture, generated by the reference implementation, covering what
   the demo does not: a /29, non-default images, a sanitised project name,
   isolated off, an unconnected device and a tab-indented frrExtra block. */
void test_mixed_topology_matches_its_fixture () {
    var state = parse_topology (golden ("mixed.netlab.json"));
    var result = compile (state);
    var expected = golden ("mixed.docker-compose.yml");

    if (result.yaml == expected) {
        return;
    }

    var actual_lines = result.yaml.split ("\n");
    var expected_lines = expected.split ("\n");
    for (var i = 0; i < int.max (actual_lines.length, expected_lines.length); i++) {
        var a = i < actual_lines.length ? actual_lines[i] : "<end of file>";
        var b = i < expected_lines.length ? expected_lines[i] : "<end of file>";
        if (a != b) {
            Test.fail_printf ("line %d differs:\n  expected: %s\n    actual: %s", i + 1, b, a);
            return;
        }
    }
    Test.fail_printf ("output differs from the fixture only in length");
}

void test_switches_are_never_services () {
    var yaml = compile (demo_state ()).yaml;

    /* sw1 and sw2 appear as networks and as interface descriptions, but never
       as a service or a container. */
    assert (has_line (yaml, "  sw1:"));                  /* present, but as a network */
    assert (!yaml.contains ("container_name: sw1"));
    assert (!yaml.contains ("container_name: sw2"));
    assert (count (yaml, "container_name:") == 4);       /* pc1, r1, r2, srv1 */

    /* Every router gets its own frr.conf. */
    assert (has_line (yaml, "  r1_frr:"));
    assert (has_line (yaml, "  r2_frr:"));
    assert (count (yaml, "_frr:") == 2);
}

void test_interface_priority () {
    var yaml = compile (demo_state ()).yaml;

    /* Docker attaches the highest priority first, which is what pins eth0 to
       the first link that was drawn. */
    assert (count (yaml, "priority: 100") == 4);         /* one eth0 per device */
    assert (count (yaml, "priority: 99") == 2);          /* both routers have an eth1 */
    assert (!yaml.contains ("priority: 98"));
}

void test_unconnected_device_gets_network_mode_none () {
    var state = parse_topology ("""
        { "nodes": [ { "id": "n1", "type": "pc", "name": "pc1" } ], "links": [] }
    """);

    var yaml = compile (state).yaml;

    /* An empty networks map would be invalid, so the device is detached. */
    assert (has_line (yaml, "    network_mode: none"));
    assert (!yaml.contains ("    networks:"));

    /* No networks at all still has to be a mapping. */
    assert (yaml.contains ("networks:\n  {}\n"));
}

void test_isolated_toggles_internal_on_every_network () {
    var state = demo_state ();

    assert (state.isolated);
    assert (count (compile (state).yaml, "    internal: true") == 3);

    state.isolated = false;
    assert (!compile (state).yaml.contains ("internal:"));
}

void test_host_commands () {
    var yaml = compile (demo_state ()).yaml;

    /* docker's own default route is removed first, tolerating its absence. */
    assert (has_line (yaml,
        "    command: [\"sh\", \"-c\", \"ip route del default 2>/dev/null || true; " +
        "ip route add default via 10.0.1.1; sleep infinity\"]"));
    assert (has_line (yaml,
        "    command: [\"sh\", \"-c\", \"ip route del default 2>/dev/null || true; " +
        "ip route add default via 10.0.2.1; python -m http.server 80\"]"));
}

void test_host_without_a_gateway_skips_the_route_steps () {
    var state = parse_topology ("""
        { "nodes": [
            { "id": "n1", "type": "pc",     "name": "pc1" },
            { "id": "n2", "type": "server", "name": "srv1", "httpPort": "8080" },
            { "id": "n3", "type": "switch", "name": "sw1", "subnet": "10.0.1.0/24" }
          ], "links": [
            { "id": "l1", "a": "n1", "b": "n3", "ips": { "n1": "10.0.1.10" } },
            { "id": "l2", "a": "n2", "b": "n3", "ips": { "n2": "10.0.1.11" } }
          ] }
    """);

    var yaml = compile (state).yaml;

    assert (has_line (yaml, "    command: [\"sh\", \"-c\", \"sleep infinity\"]"));
    assert (has_line (yaml, "    command: [\"sh\", \"-c\", \"python -m http.server 8080\"]"));
    assert (!yaml.contains ("ip route"));
}

void test_frr_extra_is_indented_with_tabs_expanded () {
    var state = demo_state ();
    state.node_by_id ("n3").frr_extra = "router bgp 65000\n\tbgp router-id 1.1.1.1\n\n\t\tneighbor x  ";

    var yaml = compile (state).yaml;

    assert (has_line (yaml, "      router bgp 65000"));
    assert (has_line (yaml, "        bgp router-id 1.1.1.1"));   /* one tab -> two spaces */
    assert (has_line (yaml, "          neighbor x"));            /* two tabs, trailing space trimmed */
    assert (yaml.contains ("\n\n"));                             /* the blank line survives */
    assert (!yaml.contains ("\t"));
}

void test_blank_frr_extra_emits_no_block () {
    var state = demo_state ();
    state.node_by_id ("n3").frr_extra = "   \n  ";

    var yaml = compile (state).yaml;

    /* r1's config goes straight from the last interface to `line vty`. */
    assert (yaml.contains ("       ip address 10.0.3.1/24\n      !\n      line vty\n"));
}

void test_configs_are_always_emitted () {
    var state = parse_topology ("""
        { "nodes": [ { "id": "n1", "type": "pc", "name": "pc1" } ], "links": [] }
    """);

    var yaml = compile (state).yaml;

    /* Both FRR configs ship even with no routers, so adding one later does not
       require regenerating from scratch. */
    assert (has_line (yaml, "  frr_daemons:"));
    assert (has_line (yaml, "  frr_vtysh:"));
    assert (has_line (yaml, "      service integrated-vtysh-config"));
    assert (!yaml.contains ("_frr:"));
}

void test_header_sections_are_conditional () {
    var routers_only = parse_topology ("""
        { "nodes": [ { "id": "n1", "type": "router", "name": "r1" } ], "links": [] }
    """);
    var hosts_only = parse_topology ("""
        { "nodes": [ { "id": "n1", "type": "pc", "name": "pc1" } ], "links": [] }
    """);

    var routers_yaml = compile (routers_only).yaml;
    assert (routers_yaml.contains ("# Router CLI:"));
    assert (routers_yaml.contains ("#   docker exec -it r1 vtysh"));
    assert (!routers_yaml.contains ("# Host shells:"));

    var hosts_yaml = compile (hosts_only).yaml;
    assert (!hosts_yaml.contains ("# Router CLI:"));
    assert (hosts_yaml.contains ("# Host shells:"));
    assert (hosts_yaml.contains ("#   docker exec -it pc1 sh"));
}

void test_project_name_and_images () {
    var state = demo_state ();
    assert (compile (state).yaml.contains ("\nname: netlab-demo\n"));

    state.router_image = "frr:11";
    state.host_image = "alpine:edge";
    state.server_image = "python:3.13";

    var yaml = compile (state).yaml;
    assert (count (yaml, "    image: frr:11") == 2);
    assert (count (yaml, "    image: alpine:edge") == 1);
    assert (count (yaml, "    image: python:3.13") == 1);
}

void test_warnings_never_block_generation () {
    var state = demo_state ();
    state.links[0].ips.insert ("n1", "10.0.9.9");      /* outside sw1 */

    var result = compile (state);

    assert (has_errors (result.warnings));
    /* The YAML is still produced, and still contains the bad address. */
    assert (result.yaml.contains ("ipv4_address: 10.0.9.9"));
    assert (result.yaml.contains ("services:"));
}

int main (string[] args) {
    Test.init (ref args);

    Test.add_func ("/core/compile/golden-file", test_demo_matches_the_golden_file);
    Test.add_func ("/core/compile/mixed-fixture", test_mixed_topology_matches_its_fixture);
    Test.add_func ("/core/compile/switches-are-networks", test_switches_are_never_services);
    Test.add_func ("/core/compile/priority", test_interface_priority);
    Test.add_func ("/core/compile/network-mode-none", test_unconnected_device_gets_network_mode_none);
    Test.add_func ("/core/compile/isolated", test_isolated_toggles_internal_on_every_network);
    Test.add_func ("/core/compile/host-commands", test_host_commands);
    Test.add_func ("/core/compile/no-gateway", test_host_without_a_gateway_skips_the_route_steps);
    Test.add_func ("/core/compile/frr-extra", test_frr_extra_is_indented_with_tabs_expanded);
    Test.add_func ("/core/compile/blank-frr-extra", test_blank_frr_extra_emits_no_block);
    Test.add_func ("/core/compile/configs-always", test_configs_are_always_emitted);
    Test.add_func ("/core/compile/header", test_header_sections_are_conditional);
    Test.add_func ("/core/compile/project-and-images", test_project_name_and_images);
    Test.add_func ("/core/compile/warnings-do-not-block", test_warnings_never_block_generation);

    return Test.run ();
}
