/* compile.vala
 *
 * The compiler (SPEC section 6): state -> { yaml, warnings }. Pure — no I/O,
 * no randomness, no clock.
 *
 * The output is emitted as text lines rather than through a YAML serialiser,
 * deliberately. The inline `# eth0` comments, the flow-map configs entries and
 * the block scalars are part of the contract; a serialiser would reorder keys
 * and drop every comment.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

namespace NetworkingLab.Core {

    public class CompileResult : Object {
        public string yaml;
        public GenericArray<Diagnostic> warnings;

        public CompileResult (string yaml, GenericArray<Diagnostic> warnings) {
            this.yaml = yaml;
            this.warnings = warnings;
        }
    }

    private const string[] FRR_DAEMONS = {
        "zebra", "staticd", "ospfd", "ospf6d", "bgpd", "ripd", "isisd",
    };

    public CompileResult compile (State state) {
        var nets = networks_of (state);
        var warnings = validate (state, nets);

        var devices = new GenericArray<Node> ();
        var routers = new GenericArray<Node> ();
        var hosts = new GenericArray<Node> ();

        /* A switch is a network, never a service. */
        for (var i = 0; i < state.nodes.length; i++) {
            var node = state.nodes[i];
            if (!node.device_type.is_service ()) {
                continue;
            }
            devices.add (node);
            if (node.device_type == DeviceType.ROUTER) {
                routers.add (node);
            } else {
                hosts.add (node);
            }
        }

        var lines = new GenericArray<string> ();

        emit_header (lines, state, routers, hosts);
        emit_services (lines, state, nets, devices);
        emit_networks (lines, state, nets);
        emit_configs (lines, state, nets, routers);

        return new CompileResult (join_lines (lines), warnings);
    }

    /* ── header ─────────────────────────────────────────────────────── */

    private void emit_header (GenericArray<string> lines, State state,
                              GenericArray<Node> routers, GenericArray<Node> hosts) {
        lines.add ("# Container network lab, generated by NetLab Designer.");
        lines.add ("# Requires docker compose v2.23.1+ for inline configs.content.");
        lines.add ("#");
        lines.add ("#   docker compose up -d      start the lab");
        lines.add ("#   docker compose down       stop it and remove the networks");

        if (routers.length > 0) {
            lines.add ("#");
            lines.add ("# Router CLI:");
            for (var i = 0; i < routers.length; i++) {
                lines.add ("#   docker exec -it %s vtysh".printf (routers[i].name));
            }
        }

        if (hosts.length > 0) {
            lines.add ("#");
            lines.add ("# Host shells:");
            for (var i = 0; i < hosts.length; i++) {
                lines.add ("#   docker exec -it %s sh".printf (hosts[i].name));
            }
        }

        lines.add ("");
        lines.add ("name: %s".printf (state.project_name));
        lines.add ("");
        lines.add ("services:");
    }

    /* ── services ───────────────────────────────────────────────────── */

    private void emit_services (GenericArray<string> lines, State state,
                                GenericArray<Network> nets, GenericArray<Node> devices) {
        for (var i = 0; i < devices.length; i++) {
            var device = devices[i];
            var interfaces = interfaces_of (state, device.id, nets);

            lines.add ("  %s:".printf (device.name));
            lines.add ("    image: %s".printf (state.image_for (device.device_type)));
            lines.add ("    container_name: %s".printf (device.name));
            lines.add ("    hostname: %s".printf (device.name));

            if (device.device_type == DeviceType.ROUTER) {
                emit_router_service (lines, device);
            } else {
                emit_host_service (lines, device);
            }

            if (interfaces.length > 0) {
                /* priority pins interface order: docker attaches the highest
                   first, so eth0 is the first link that was drawn. */
                lines.add ("    networks:");
                for (var j = 0; j < interfaces.length; j++) {
                    var iface = interfaces[j];
                    lines.add ("      %s:  # %s".printf (iface.net.name, iface.eth));
                    if (iface.ip != "") {
                        lines.add ("        ipv4_address: %s".printf (iface.ip));
                    }
                    lines.add ("        priority: %d".printf (100 - j));
                }
            } else {
                lines.add ("    network_mode: none");
            }

            lines.add ("");
        }
    }

    /* rp_filter off keeps asymmetric lab paths from being dropped; NET_ADMIN
     * and SYS_ADMIN are what FRR needs to program the kernel FIB. */
    private void emit_router_service (GenericArray<string> lines, Node device) {
        lines.add ("    cap_add: [NET_ADMIN, NET_RAW, SYS_ADMIN]");
        lines.add ("    sysctls:");
        lines.add ("      net.ipv4.ip_forward: 1");
        lines.add ("      net.ipv4.conf.all.rp_filter: 0");
        lines.add ("      net.ipv4.conf.default.rp_filter: 0");
        lines.add ("    configs:");
        lines.add ("      - { source: frr_daemons, target: /etc/frr/daemons, mode: 0644 }");
        lines.add ("      - { source: frr_vtysh, target: /etc/frr/vtysh.conf, mode: 0644 }");
        lines.add ("      - { source: %s_frr, target: /etc/frr/frr.conf, mode: 0644 }".printf (device.name));
    }

    /* docker installs its own default route via the bridge gateway; the lab
     * wants the router instead, so the first step removes it, tolerating its
     * absence. */
    private void emit_host_service (GenericArray<string> lines, Node device) {
        lines.add ("    cap_add: [NET_ADMIN]");

        var steps = new GenericArray<string> ();
        if (device.gw != "") {
            steps.add ("ip route del default 2>/dev/null || true");
            steps.add ("ip route add default via %s".printf (device.gw));
        }
        if (device.device_type == DeviceType.SERVER) {
            var port = device.http_port == "" ? "80" : device.http_port;
            steps.add ("python -m http.server %s".printf (port));
        } else {
            steps.add ("sleep infinity");
        }

        lines.add ("    command: [\"sh\", \"-c\", \"%s\"]".printf (join_with (steps, "; ")));
    }

    /* ── networks ───────────────────────────────────────────────────── */

    private void emit_networks (GenericArray<string> lines, State state,
                                GenericArray<Network> nets) {
        lines.add ("networks:");

        /* An empty mapping still has to be a mapping. */
        if (nets.length == 0) {
            lines.add ("  {}");
        }

        for (var i = 0; i < nets.length; i++) {
            var net = nets[i];
            lines.add ("  %s:".printf (net.name));
            lines.add ("    driver: bridge");
            if (state.isolated) {
                lines.add ("    internal: true");
            }
            lines.add ("    ipam:");
            lines.add ("      config:");
            lines.add ("        - subnet: %s".printf (net.subnet));
            lines.add ("          gateway: %s  # reserved for docker, don't assign to devices"
                       .printf (docker_gateway (net.subnet)));
        }

        lines.add ("");
    }

    /* ── configs ────────────────────────────────────────────────────── */

    private void emit_configs (GenericArray<string> lines, State state,
                               GenericArray<Network> nets, GenericArray<Node> routers) {
        lines.add ("configs:");

        /* Both are emitted even with no routers, so a lab that grows one later
           does not need the file regenerating from scratch. */
        lines.add ("  frr_daemons:");
        lines.add ("    content: |");
        foreach (var daemon in FRR_DAEMONS) {
            lines.add ("      %s=yes".printf (daemon));
        }
        lines.add ("      vtysh_enable=yes");
        lines.add ("      zebra_options=\" -A 127.0.0.1 -s 90000000\"");
        lines.add ("      ospfd_options=\" -A 127.0.0.1\"");
        lines.add ("      ospf6d_options=\" -A ::1\"");
        lines.add ("      bgpd_options=\"  -A 127.0.0.1\"");
        lines.add ("      ripd_options=\"  -A 127.0.0.1\"");
        lines.add ("      isisd_options=\" -A 127.0.0.1\"");
        lines.add ("      staticd_options=\"-A 127.0.0.1\"");

        /* Without this file vtysh prints "Can't open configuration file" on
           every invocation — cosmetic, but it is the first thing a student
           sees. */
        lines.add ("  frr_vtysh:");
        lines.add ("    content: |");
        lines.add ("      service integrated-vtysh-config");

        for (var i = 0; i < routers.length; i++) {
            emit_router_config (lines, state, nets, routers[i]);
        }

        lines.add ("");
    }

    private void emit_router_config (GenericArray<string> lines, State state,
                                     GenericArray<Network> nets, Node router) {
        lines.add ("  %s_frr:".printf (router.name));
        lines.add ("    content: |");
        lines.add ("      frr defaults traditional");
        lines.add ("      hostname %s".printf (router.name));
        lines.add ("      service integrated-vtysh-config");
        lines.add ("      !");

        var interfaces = interfaces_of (state, router.id, nets);
        for (var i = 0; i < interfaces.length; i++) {
            var iface = interfaces[i];
            lines.add ("      interface %s".printf (iface.eth));
            lines.add ("       description %s".printf (iface.net.name));
            if (iface.ip != "") {
                lines.add ("       ip address %s/%d".printf (iface.ip, cidr_info (iface.net.subnet).length));
            }
            lines.add ("      !");
        }

        if (router.frr_extra.strip () != "") {
            /* Tabs become two spaces so the block scalar keeps its shape. */
            foreach (var line in router.frr_extra.replace ("\t", "  ").split ("\n")) {
                lines.add (("      " + line).chomp ());
            }
            lines.add ("      !");
        }

        lines.add ("      line vty");
    }

    /* ── text helpers ───────────────────────────────────────────────── */

    private string join_lines (GenericArray<string> lines) {
        var result = new StringBuilder ();
        for (var i = 0; i < lines.length; i++) {
            if (i > 0) {
                result.append_c ('\n');
            }
            result.append (lines[i]);
        }
        return result.str;
    }

    private string join_with (GenericArray<string> parts, string separator) {
        var result = new StringBuilder ();
        for (var i = 0; i < parts.length; i++) {
            if (i > 0) {
                result.append (separator);
            }
            result.append (parts[i]);
        }
        return result.str;
    }
}
